# --------------------------------
# GeyserConnect Configuration File
# --------------------------------

# The IP address that will listen for connections
address: 0.0.0.0

# The port that will listen for connections
port: 19132

# If debug messages should be sent through console
debug-mode: false

# Should we query the sever to sync the server information
query-server: false

# The amount of time in seconds between server queries if query-server is enabled
update-interval: 30

# Makes the Sub-MOTD the MOTD and vice-versa
swap-motd: false

# Server to send client to and default information to reply with if query-server is false or server is offline
server-info:
  # MOTD to display
  motd: "GeyserConnect Proxy"
  #Sub-MOTD to display. Will be "GeyserConnect" by default if left blank
  submotd: "GeyserConnect"
  # Shown player count
  players: 0
  # Shown max player count
  max-players: 100
  # Connection information for your backend server
  ip: mco.cubecraft.net
  port: 19132

# Config for the Geyser listener
geyser:
  # If debug messages should be sent through console, has to be enabled in both places to work
  debug-mode: false
